export interface PurchaseNotification {
  id: string;
  customerName: string;
  city: string;
  productName: string;
  productImage: string;
  productSlug?: string;
  timeAgo: string;
  verified?: boolean;
}

export const CUSTOMER_NOTIFICATIONS_STORAGE_KEY = 'deeksha_purchase_notifications';

export const defaultPurchaseNotifications: PurchaseNotification[] = [
  { id: 'notif-1', customerName: 'Priya', city: 'Delhi', productName: 'Royal Pearl Drop Earrings', productImage: '/images/earrings_category.png', productSlug: 'royal-pearl-drops', timeAgo: '2 minutes ago', verified: true },
  { id: 'notif-2', customerName: 'Ananya', city: 'Mumbai', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '4 minutes ago', verified: true },
  { id: 'notif-3', customerName: 'Sneha', city: 'Gurugram', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '7 minutes ago', verified: true },
  { id: 'notif-4', customerName: 'Ritu', city: 'Bangalore', productName: 'Minimalist Link Chain Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'minimalist-link-chain', timeAgo: '10 minutes ago', verified: true },
  { id: 'notif-5', customerName: 'Pooja', city: 'Mumbai', productName: 'Rose Gold Floral Studs', productImage: '/images/earrings_category.png', productSlug: 'rose-gold-floral-studs', timeAgo: '12 minutes ago', verified: true },
  { id: 'notif-6', customerName: 'Divya', city: 'Ahmedabad', productName: 'Emperor Crown Charm', productImage: '/images/charm_category.png', productSlug: 'emperor-crown-charm', timeAgo: '15 minutes ago', verified: true },
  { id: 'notif-7', customerName: 'Kavita', city: 'Gurugram', productName: 'Eternity Band Ring', productImage: '/images/rings_category.png', productSlug: 'eternity-band-ring', timeAgo: '18 minutes ago', verified: true },
  { id: 'notif-8', customerName: 'Neha', city: 'Hyderabad', productName: 'Tennis Gemstone Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'tennis-gemstone-bracelet', timeAgo: '23 minutes ago', verified: true },
  { id: 'notif-9', customerName: 'Aarti', city: 'Lucknow', productName: 'Vintage Emerald Cut Ring', productImage: '/images/charm_category.png', productSlug: 'vintage-emerald-ring', timeAgo: '27 minutes ago', verified: true },
  { id: 'notif-10', customerName: 'Swati', city: 'Surat', productName: 'Charm Carrier Bangle', productImage: '/images/hero_slide_2.png', productSlug: 'charm-carrier-bangle', timeAgo: '31 minutes ago', verified: true },
  { id: 'notif-11', customerName: 'Isha', city: 'Indore', productName: 'Royal Pearl Drop Earrings', productImage: '/images/hero_slide_1.png', productSlug: 'royal-pearl-drops', timeAgo: '35 minutes ago', verified: true },
  { id: 'notif-12', customerName: 'Deepika', city: 'Noida', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '39 minutes ago', verified: true },
  { id: 'notif-13', customerName: 'Simran', city: 'Gurugram', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '44 minutes ago', verified: true },
  { id: 'notif-14', customerName: 'Sweta', city: 'Amritsar', productName: 'Rose Gold Floral Studs', productImage: '/images/earrings_category.png', productSlug: 'rose-gold-floral-studs', timeAgo: '48 minutes ago', verified: true },
  { id: 'notif-15', customerName: 'Radhika', city: 'Ludhiana', productName: 'Minimalist Link Chain Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'minimalist-link-chain', timeAgo: '52 minutes ago', verified: true },
  { id: 'notif-16', customerName: 'Sonam', city: 'Bhopal', productName: 'Emperor Crown Charm', productImage: '/images/charm_category.png', productSlug: 'emperor-crown-charm', timeAgo: '56 minutes ago', verified: true },
  { id: 'notif-17', customerName: 'Mansi', city: 'Patna', productName: 'Eternity Band Ring', productImage: '/images/rings_category.png', productSlug: 'eternity-band-ring', timeAgo: '1 hour ago', verified: true },
  { id: 'notif-18', customerName: 'Preeti', city: 'Vadodara', productName: 'Tennis Gemstone Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'tennis-gemstone-bracelet', timeAgo: '1 hour ago', verified: true },
  { id: 'notif-19', customerName: 'Payal', city: 'Agra', productName: 'Royal Pearl Drop Earrings', productImage: '/images/hero_slide_1.png', productSlug: 'royal-pearl-drops', timeAgo: '1 hour ago', verified: true },
  { id: 'notif-20', customerName: 'Komal', city: 'Varanasi', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '1 hour ago', verified: true },
  { id: 'notif-21', customerName: 'Riddhi', city: 'Kochi', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '2 hours ago', verified: true },
  { id: 'notif-22', customerName: 'Muskan', city: 'Nagpur', productName: 'Rose Gold Floral Studs', productImage: '/images/earrings_category.png', productSlug: 'rose-gold-floral-studs', timeAgo: '2 hours ago', verified: true },
  { id: 'notif-23', customerName: 'Garima', city: 'Rajkot', productName: 'Charm Carrier Bangle', productImage: '/images/hero_slide_2.png', productSlug: 'charm-carrier-bangle', timeAgo: '2 hours ago', verified: true },
  { id: 'notif-24', customerName: 'Sakshi', city: 'Jodhpur', productName: 'Vintage Emerald Cut Ring', productImage: '/images/charm_category.png', productSlug: 'vintage-emerald-ring', timeAgo: '2 hours ago', verified: true },
  { id: 'notif-25', customerName: 'Kajal', city: 'Udaipur', productName: 'Tennis Gemstone Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'tennis-gemstone-bracelet', timeAgo: '3 hours ago', verified: true },
  { id: 'notif-26', customerName: 'Priyanka', city: 'Kanpur', productName: 'Royal Pearl Drop Earrings', productImage: '/images/earrings_category.png', productSlug: 'royal-pearl-drops', timeAgo: '3 hours ago', verified: true },
  { id: 'notif-27', customerName: 'Ankita', city: 'Nashik', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '3 hours ago', verified: true },
  { id: 'notif-28', customerName: 'Jyoti', city: 'Dehradun', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '3 hours ago', verified: true },
  { id: 'notif-29', customerName: 'Bhavna', city: 'Shimla', productName: 'Minimalist Link Chain Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'minimalist-link-chain', timeAgo: '4 hours ago', verified: true },
  { id: 'notif-30', customerName: 'Rashmi', city: 'Coimbatore', productName: 'Rose Gold Floral Studs', productImage: '/images/earrings_category.png', productSlug: 'rose-gold-floral-studs', timeAgo: '4 hours ago', verified: true },
  { id: 'notif-31', customerName: 'Juhi', city: 'Mysuru', productName: 'Emperor Crown Charm', productImage: '/images/charm_category.png', productSlug: 'emperor-crown-charm', timeAgo: '4 hours ago', verified: true },
  { id: 'notif-32', customerName: 'Barkha', city: 'Jammu', productName: 'Eternity Band Ring', productImage: '/images/rings_category.png', productSlug: 'eternity-band-ring', timeAgo: '4 hours ago', verified: true },
  { id: 'notif-33', customerName: 'Niharika', city: 'Ranchi', productName: 'Tennis Gemstone Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'tennis-gemstone-bracelet', timeAgo: '5 hours ago', verified: true },
  { id: 'notif-34', customerName: 'Shruti', city: 'Guwahati', productName: 'Royal Pearl Drop Earrings', productImage: '/images/hero_slide_1.png', productSlug: 'royal-pearl-drops', timeAgo: '5 hours ago', verified: true },
  { id: 'notif-35', customerName: 'Reena', city: 'Bhubaneshwar', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '5 hours ago', verified: true },
  { id: 'notif-36', customerName: 'Sonali', city: 'Madurai', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '5 hours ago', verified: true },
  { id: 'notif-37', customerName: 'Nidhi', city: 'Kozhikode', productName: 'Rose Gold Floral Studs', productImage: '/images/earrings_category.png', productSlug: 'rose-gold-floral-studs', timeAgo: '6 hours ago', verified: true },
  { id: 'notif-38', customerName: 'Kriti', city: 'Raipur', productName: 'Charm Carrier Bangle', productImage: '/images/hero_slide_2.png', productSlug: 'charm-carrier-bangle', timeAgo: '6 hours ago', verified: true },
  { id: 'notif-39', customerName: 'Pragya', city: 'Visakhapatnam', productName: 'Vintage Emerald Cut Ring', productImage: '/images/charm_category.png', productSlug: 'vintage-emerald-ring', timeAgo: '6 hours ago', verified: true },
  { id: 'notif-40', customerName: 'Archana', city: 'Meerut', productName: 'Minimalist Link Chain Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'minimalist-link-chain', timeAgo: '6 hours ago', verified: true },
  { id: 'notif-41', customerName: 'Charu', city: 'Ghaziabad', productName: 'Eternity Band Ring', productImage: '/images/rings_category.png', productSlug: 'eternity-band-ring', timeAgo: '7 hours ago', verified: true },
  { id: 'notif-42', customerName: 'Urvashi', city: 'Faridabad', productName: 'Tennis Gemstone Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'tennis-gemstone-bracelet', timeAgo: '7 hours ago', verified: true },
  { id: 'notif-43', customerName: 'Mahi', city: 'Panaji', productName: 'Royal Pearl Drop Earrings', productImage: '/images/earrings_category.png', productSlug: 'royal-pearl-drops', timeAgo: '7 hours ago', verified: true },
  { id: 'notif-44', customerName: 'Vandana', city: 'Thane', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '7 hours ago', verified: true },
  { id: 'notif-45', customerName: 'Shilpa', city: 'Navi Mumbai', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '8 hours ago', verified: true },
  { id: 'notif-46', customerName: 'Smriti', city: 'Jalandhar', productName: 'Rose Gold Floral Studs', productImage: '/images/earrings_category.png', productSlug: 'rose-gold-floral-studs', timeAgo: '8 hours ago', verified: true },
  { id: 'notif-47', customerName: 'Chetna', city: 'Gwalior', productName: 'Emperor Crown Charm', productImage: '/images/charm_category.png', productSlug: 'emperor-crown-charm', timeAgo: '8 hours ago', verified: true },
  { id: 'notif-48', customerName: 'Deepa', city: 'Bareilly', productName: 'Charm Carrier Bangle', productImage: '/images/hero_slide_2.png', productSlug: 'charm-carrier-bangle', timeAgo: '8 hours ago', verified: true },
  { id: 'notif-49', customerName: 'Minakshi', city: 'Kota', productName: 'Vintage Emerald Cut Ring', productImage: '/images/charm_category.png', productSlug: 'vintage-emerald-ring', timeAgo: '9 hours ago', verified: true },
  { id: 'notif-50', customerName: 'Twinkle', city: 'Aligarh', productName: 'Tennis Gemstone Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'tennis-gemstone-bracelet', timeAgo: '9 hours ago', verified: true },
  { id: 'notif-51', customerName: 'Gunjan', city: 'Moradabad', productName: 'Royal Pearl Drop Earrings', productImage: '/images/hero_slide_1.png', productSlug: 'royal-pearl-drops', timeAgo: '9 hours ago', verified: true },
  { id: 'notif-52', customerName: 'Richa', city: 'Saharanpur', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '9 hours ago', verified: true },
  { id: 'notif-53', customerName: 'Mona', city: 'Gorakhpur', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '10 hours ago', verified: true },
  { id: 'notif-54', customerName: 'Sanjana', city: 'Bikaner', productName: 'Rose Gold Floral Studs', productImage: '/images/earrings_category.png', productSlug: 'rose-gold-floral-studs', timeAgo: '10 hours ago', verified: true },
  { id: 'notif-55', customerName: 'Riya', city: 'Solapur', productName: 'Minimalist Link Chain Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'minimalist-link-chain', timeAgo: '10 hours ago', verified: true },
  { id: 'notif-56', customerName: 'Yashvi', city: 'Amravati', productName: 'Emperor Crown Charm', productImage: '/images/charm_category.png', productSlug: 'emperor-crown-charm', timeAgo: '10 hours ago', verified: true },
  { id: 'notif-57', customerName: 'Navya', city: 'Nanded', productName: 'Eternity Band Ring', productImage: '/images/rings_category.png', productSlug: 'eternity-band-ring', timeAgo: '11 hours ago', verified: true },
  { id: 'notif-58', customerName: 'Swaran', city: 'Cuttack', productName: 'Tennis Gemstone Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'tennis-gemstone-bracelet', timeAgo: '11 hours ago', verified: true },
  { id: 'notif-59', customerName: 'Avani', city: 'Firozabad', productName: 'Royal Pearl Drop Earrings', productImage: '/images/earrings_category.png', productSlug: 'royal-pearl-drops', timeAgo: '11 hours ago', verified: true },
  { id: 'notif-60', customerName: 'Diya', city: 'Bhilai', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '11 hours ago', verified: true },
  { id: 'notif-61', customerName: 'Khushi', city: 'Salem', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '12 hours ago', verified: true },
  { id: 'notif-62', customerName: 'Aarohi', city: 'Jhansi', productName: 'Charm Carrier Bangle', productImage: '/images/hero_slide_2.png', productSlug: 'charm-carrier-bangle', timeAgo: '12 hours ago', verified: true },
  { id: 'notif-63', customerName: 'Shanaya', city: 'Nellore', productName: 'Rose Gold Floral Studs', productImage: '/images/earrings_category.png', productSlug: 'rose-gold-floral-studs', timeAgo: '12 hours ago', verified: true },
  { id: 'notif-64', customerName: 'Tara', city: 'Muzaffarnagar', productName: 'Minimalist Link Chain Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'minimalist-link-chain', timeAgo: '12 hours ago', verified: true },
  { id: 'notif-65', customerName: 'Ishani', city: 'Mathura', productName: 'Vintage Emerald Cut Ring', productImage: '/images/charm_category.png', productSlug: 'vintage-emerald-ring', timeAgo: '13 hours ago', verified: true },
  { id: 'notif-66', customerName: 'Kiara', city: 'Kollam', productName: 'Eternity Band Ring', productImage: '/images/rings_category.png', productSlug: 'eternity-band-ring', timeAgo: '13 hours ago', verified: true },
  { id: 'notif-67', customerName: 'Myra', city: 'Patiala', productName: 'Tennis Gemstone Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'tennis-gemstone-bracelet', timeAgo: '13 hours ago', verified: true },
  { id: 'notif-68', customerName: 'Anushree', city: 'Rohtak', productName: 'Royal Pearl Drop Earrings', productImage: '/images/hero_slide_1.png', productSlug: 'royal-pearl-drops', timeAgo: '13 hours ago', verified: true },
  { id: 'notif-69', customerName: 'Devika', city: 'Bhilwara', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '14 hours ago', verified: true },
  { id: 'notif-70', customerName: 'Kirti', city: 'Korba', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '14 hours ago', verified: true },
  { id: 'notif-71', customerName: 'Malini', city: 'Muzaffarpur', productName: 'Rose Gold Floral Studs', productImage: '/images/earrings_category.png', productSlug: 'rose-gold-floral-studs', timeAgo: '14 hours ago', verified: true },
  { id: 'notif-72', customerName: 'Trisha', city: 'Ahmednagar', productName: 'Emperor Crown Charm', productImage: '/images/charm_category.png', productSlug: 'emperor-crown-charm', timeAgo: '14 hours ago', verified: true },
  { id: 'notif-73', customerName: 'Lavanya', city: 'Rourkela', productName: 'Charm Carrier Bangle', productImage: '/images/hero_slide_2.png', productSlug: 'charm-carrier-bangle', timeAgo: '15 hours ago', verified: true },
  { id: 'notif-74', customerName: 'Vaishnavi', city: 'Dhanbad', productName: 'Minimalist Link Chain Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'minimalist-link-chain', timeAgo: '15 hours ago', verified: true },
  { id: 'notif-75', customerName: 'Gayatri', city: 'Guntur', productName: 'Vintage Emerald Cut Ring', productImage: '/images/charm_category.png', productSlug: 'vintage-emerald-ring', timeAgo: '15 hours ago', verified: true },
  { id: 'notif-76', customerName: 'Sayali', city: 'Warangal', productName: 'Eternity Band Ring', productImage: '/images/rings_category.png', productSlug: 'eternity-band-ring', timeAgo: '15 hours ago', verified: true },
  { id: 'notif-77', customerName: 'Aditi', city: 'Siliguri', productName: 'Tennis Gemstone Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'tennis-gemstone-bracelet', timeAgo: '16 hours ago', verified: true },
  { id: 'notif-78', customerName: 'Tanvi', city: 'Ujjain', productName: 'Royal Pearl Drop Earrings', productImage: '/images/earrings_category.png', productSlug: 'royal-pearl-drops', timeAgo: '16 hours ago', verified: true },
  { id: 'notif-79', customerName: 'Vrinda', city: 'Sangli', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '16 hours ago', verified: true },
  { id: 'notif-80', customerName: 'Srushti', city: 'Erode', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '16 hours ago', verified: true },
  { id: 'notif-81', customerName: 'Sanika', city: 'Tirunelveli', productName: 'Rose Gold Floral Studs', productImage: '/images/earrings_category.png', productSlug: 'rose-gold-floral-studs', timeAgo: '17 hours ago', verified: true },
  { id: 'notif-82', customerName: 'Janhavi', city: 'Mangalore', productName: 'Emperor Crown Charm', productImage: '/images/charm_category.png', productSlug: 'emperor-crown-charm', timeAgo: '17 hours ago', verified: true },
  { id: 'notif-83', customerName: 'Rutuja', city: 'Belgaum', productName: 'Charm Carrier Bangle', productImage: '/images/hero_slide_2.png', productSlug: 'charm-carrier-bangle', timeAgo: '17 hours ago', verified: true },
  { id: 'notif-84', customerName: 'Tejaswini', city: 'Gaya', productName: 'Minimalist Link Chain Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'minimalist-link-chain', timeAgo: '17 hours ago', verified: true },
  { id: 'notif-85', customerName: 'Archita', city: 'Tirupati', productName: 'Vintage Emerald Cut Ring', productImage: '/images/charm_category.png', productSlug: 'vintage-emerald-ring', timeAgo: '18 hours ago', verified: true },
  { id: 'notif-86', customerName: 'Shreya', city: 'Hospet', productName: 'Eternity Band Ring', productImage: '/images/rings_category.png', productSlug: 'eternity-band-ring', timeAgo: '18 hours ago', verified: true },
  { id: 'notif-87', customerName: 'Bipasha', city: 'Durgapur', productName: 'Tennis Gemstone Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'tennis-gemstone-bracelet', timeAgo: '18 hours ago', verified: true },
  { id: 'notif-88', customerName: 'Aparna', city: 'Asansol', productName: 'Royal Pearl Drop Earrings', productImage: '/images/hero_slide_1.png', productSlug: 'royal-pearl-drops', timeAgo: '18 hours ago', verified: true },
  { id: 'notif-89', customerName: 'Soumya', city: 'Kolhapur', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '19 hours ago', verified: true },
  { id: 'notif-90', customerName: 'Pratibha', city: 'Latur', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '19 hours ago', verified: true },
  { id: 'notif-91', customerName: 'Namrata', city: 'Ajmer', productName: 'Rose Gold Floral Studs', productImage: '/images/earrings_category.png', productSlug: 'rose-gold-floral-studs', timeAgo: '19 hours ago', verified: true },
  { id: 'notif-92', customerName: 'Reeva', city: 'Anantapur', productName: 'Emperor Crown Charm', productImage: '/images/charm_category.png', productSlug: 'emperor-crown-charm', timeAgo: '19 hours ago', verified: true },
  { id: 'notif-93', customerName: 'Mahima', city: 'Karnal', productName: 'Charm Carrier Bangle', productImage: '/images/hero_slide_2.png', productSlug: 'charm-carrier-bangle', timeAgo: '20 hours ago', verified: true },
  { id: 'notif-94', customerName: 'Kanchan', city: 'Panipat', productName: 'Minimalist Link Chain Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'minimalist-link-chain', timeAgo: '20 hours ago', verified: true },
  { id: 'notif-95', customerName: 'Varsha', city: 'Sonipat', productName: 'Vintage Emerald Cut Ring', productImage: '/images/charm_category.png', productSlug: 'vintage-emerald-ring', timeAgo: '20 hours ago', verified: true },
  { id: 'notif-96', customerName: 'Nivedita', city: 'Hissar', productName: 'Eternity Band Ring', productImage: '/images/rings_category.png', productSlug: 'eternity-band-ring', timeAgo: '20 hours ago', verified: true },
  { id: 'notif-97', customerName: 'Yamini', city: 'Bathinda', productName: 'Tennis Gemstone Bracelet', productImage: '/images/bracelets_category.png', productSlug: 'tennis-gemstone-bracelet', timeAgo: '21 hours ago', verified: true },
  { id: 'notif-98', customerName: 'Jasleen', city: 'Mohali', productName: 'Royal Pearl Drop Earrings', productImage: '/images/earrings_category.png', productSlug: 'royal-pearl-drops', timeAgo: '21 hours ago', verified: true },
  { id: 'notif-99', customerName: 'Harpreet', city: 'Panchkula', productName: 'Golden Solitaire Ring', productImage: '/images/rings_category.png', productSlug: 'golden-solitaire-ring', timeAgo: '22 hours ago', verified: true },
  { id: 'notif-100', customerName: 'Raveena', city: 'Shimoga', productName: 'Classic Heart Pendant Necklace', productImage: '/images/necklaces_category.png', productSlug: 'classic-heart-pendant', timeAgo: '23 hours ago', verified: true }
];

export function normalizePurchaseNotifications(raw: any): PurchaseNotification[] {
  if (!Array.isArray(raw) || raw.length < 50) return defaultPurchaseNotifications;
  return raw.map((item, index) => ({
    id: String(item.id || `notif-${index + 1}`),
    customerName: String(item.customerName || 'Happy Customer'),
    city: String(item.city || 'India'),
    productName: String(item.productName || 'Royal Pearl Drops'),
    productImage: String(item.productImage || '/images/earrings_category.png'),
    productSlug: item.productSlug ? String(item.productSlug) : '',
    timeAgo: String(item.timeAgo || 'Recently'),
    verified: item.verified !== undefined ? Boolean(item.verified) : true
  }));
}
